backend/hir: add prototype/WIP intermediate representation + typecheck
This can currently typecheck simple programs. Trying to run
examples/type_error.lri will generate the following diagnostic:

error: expected {integer}, got string
  |
1 | fn main() {
2 |     f("hi world");
  |       ^^^^^^^^^^ type error detected here
  |
  = note: this may be inaccurate;
          these diagnostics will improve in the future

...while running examples/extern.lri correctly prints
"Hello extern world!".

Unfortunately, the code is somewhat slipshod right now, so it will
probably balk at complex (or even simple) scripts. Further work will
be necessary.

This currently breaks examples/test.lri as it infers that `print` has
the type `(String) -> ()`, but it's currently used as if it accepted
any type. This can be worked around easily, but that might be too much
for one commit :P.